# Generated by Django 6.0.1 on 2026-01-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    """
       Третя міграція проєкту (0003_schedule_alter_zvt_department_alter_zvt_name).
       Мета змінити параметри полів 'name' та 'department' у моделі ZVT,
    """
    dependencies = [
        ('registry', '0002_zvt_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва документа (напр. Графік на 2026 рік)')),
                ('file', models.FileField(upload_to='schedules/%Y/', verbose_name='Файл графіка (PDF/Excel)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
            ],
            options={
                'verbose_name': 'Графік повірки',
                'verbose_name_plural': 'Графіки повірки',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='zvt',
            name='department',
            field=models.CharField(choices=[('ЦЕХ-1', 'Цех №1'), ('ЦЕХ-2', 'Цех №2'), ('ЛАБОРАТОРІЯ', 'Центральна лабораторія'), ('ЕНЕРГО', 'Енергодільниця')], max_length=100, verbose_name='Дільниця'),
        ),
        migrations.AlterField(
            model_name='zvt',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва ЗВТ'),
        ),
    ]
