# Generated by Django 6.0.1 on 2026-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_zvt_department_alter_zvt_measurement_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvt',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис приладу'),
        ),
    ]
