# Generated by Django 6.0.1 on 2026-01-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_zvt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvt',
            name='control_dimensions',
            field=models.TextField(blank=True, null=True, verbose_name='Контрольні розміри'),
        ),
        migrations.AddField(
            model_name='zvt',
            name='technical_drawing',
            field=models.FileField(blank=True, null=True, upload_to='drawings/%Y/', verbose_name='Схема / Креслення'),
        ),
    ]
